### ISSUE TITLE
website is garbled mess

### ISSUE THREAD

**Issue by devomaa** [dimaguy/MinecraftHQ#2]
possible fix: provide encoding to web browser

**Comment by dimaguy** [comment]
The encoding is literally in the third line of index.html.
Could you provide screenshots?

**Comment by devomaa** [comment]
![Screenshot from 2021-04-11 16-12-14](https://user-images.githubusercontent.com/25231103/114305395-b7af4180-9ae0-11eb-9863-8e463531a178.png)

**Comment by dimaguy** [comment]
Interesting. I will test the issue later today and a fix should be issued by tomorrow

**Comment by devomaa** [comment]
the system is ubuntu 21.04 (hiruste) if that helps :)
if you dont see it on the download page its a pre-release, tho its coming out in around 12 days

**Comment by dimaguy** [comment]
While I am unable to provide a fix today, if you want to fiddle around instead of waiting I recommend trying to disable http/2 or https on the fastify const, maybe enable the logger (logger: true on the const) and send console pics

**Comment by dimaguy** [comment]
Seems like enabling experimental http/2 support and not testing it after was a bad idea.
1db0aa0 closes this
